import type { AnalysisListItem, WorkspaceAnalysis } from './types';

export const mockAnalyses: AnalysisListItem[] = [
  {
    id: 'demo-job-analysis',
    title: '生成AIプロダクト開発｜Next.js / TypeScript',
    url: 'https://example.com/jobs/ai-product-engineer',
    pageType: 'job',
    status: 'completed',
    summary:
      'AIプロダクトの設計から実装までを担う副業案件。現在のスキルと高い親和性があります。',
    recommendationScore: 92,
    createdAt: '2026-07-23T11:24:00+09:00',
    tags: ['Next.js', 'AI', '副業'],
  },
  {
    id: 'demo-article-analysis',
    title: 'LLMアプリケーションの評価設計入門',
    url: 'https://example.dev/articles/llm-evaluation',
    pageType: 'article',
    status: 'completed',
    summary:
      'LLM評価の基礎から実運用の観測指標まで、段階的に整理された技術記事です。',
    recommendationScore: 86,
    createdAt: '2026-07-22T18:10:00+09:00',
    tags: ['LLM', 'Evaluation'],
  },
  {
    id: 'demo-github-analysis',
    title: 'open-agent-workbench',
    url: 'https://github.com/example/open-agent-workbench',
    pageType: 'github',
    status: 'running',
    summary:
      '制御可能なAIワークフローを構築するTypeScript製リポジトリを分析中です。',
    recommendationScore: 78,
    createdAt: '2026-07-22T09:42:00+09:00',
    tags: ['GitHub', 'Agent'],
  },
  {
    id: 'demo-company-analysis',
    title: 'Orbital Works — AI operations platform',
    url: 'https://example.com/company/orbital-works',
    pageType: 'company',
    status: 'completed',
    summary:
      '業務オペレーションをAIで再設計するB2B SaaS。差別化要素を抽出しました。',
    recommendationScore: 81,
    createdAt: '2026-07-20T16:08:00+09:00',
    tags: ['SaaS', 'Company'],
  },
  {
    id: 'demo-general-analysis',
    title: '2026年 Webプロダクト市場レポート',
    url: 'https://example.org/reports/web-product-2026',
    pageType: 'general',
    status: 'failed',
    summary: '本文が短く、信頼性の判断に必要な出典情報を取得できませんでした。',
    recommendationScore: null,
    createdAt: '2026-07-18T13:30:00+09:00',
    tags: ['Report'],
  },
];

export const demoWorkspace: WorkspaceAnalysis = {
  item: mockAnalyses[0]!,
  capturedPage: {
    title: '生成AIプロダクト開発｜Next.js / TypeScript',
    url: 'https://example.com/jobs/ai-product-engineer',
    metaDescription:
      '生成AIを活用した新規プロダクトの設計・開発を担うフルスタックエンジニアを募集します。',
    selectedText:
      '週2〜3日、フルリモート。プロダクト設計から関われる方を歓迎します。',
    capturedAt: '2026-07-23T11:24:00+09:00',
    excerpt:
      '私たちは企業のナレッジ活用を支援する生成AIプロダクトを開発しています。Next.js、TypeScript、Supabaseを用いた機能開発に加え、LLMワークフローの設計と品質改善を担当します。',
  },
  steps: [
    {
      id: 'capture',
      name: 'Browser Capture',
      purpose: '閲覧ページの情報を安全に受け取る',
      status: 'completed',
      description: 'タイトル、URL、本文、選択テキストを受信しました。',
      input: 'Chrome Side Panelから送信',
      output: '本文 8,426文字 / 選択テキスト 38文字',
      tool: 'Capture API',
      durationMs: 118,
    },
    {
      id: 'parse',
      name: 'Content Parsing',
      purpose: '分析に不要な情報を除き本文を整える',
      status: 'completed',
      description: '空白と重複を除去し、最大文字数の範囲に整形しました。',
      input: 'プレーンテキスト 8,426文字',
      output: '正規化済み本文 7,918文字',
      tool: 'Text normalizer',
      durationMs: 42,
    },
    {
      id: 'classify',
      name: 'Page Classification',
      purpose: 'ページ種別と分析方針を決める',
      status: 'completed',
      description: '求人・副業案件ページとして分類しました。',
      input: 'タイトル / URL / 正規化本文',
      output: 'job（confidence 0.96）',
      tool: 'Page classifier',
      durationMs: 684,
    },
    {
      id: 'context',
      name: 'Context Loading',
      purpose: 'ユーザーの希望条件とスキルを参照する',
      status: 'completed',
      description: 'プロフィールから比較に必要な情報だけを参照しました。',
      input: '保有スキル / 希望条件',
      output: '比較コンテキスト 6項目',
      tool: 'Profile repository',
      durationMs: 93,
    },
    {
      id: 'strategy',
      name: 'Tool Selection',
      purpose: '許可された分析ツールを選択する',
      status: 'completed',
      description: '求人分析ストラテジーと適合度評価を選択しました。',
      input: 'pageType: job',
      output: 'job-analysis-v1',
      tool: 'Strategy registry',
      durationMs: 16,
    },
    {
      id: 'analysis',
      name: 'Analysis',
      purpose: '要件とプロフィールの適合性を評価する',
      status: 'completed',
      description: '案件要件、条件、キャリア価値を構造化して分析しました。',
      input: '求人本文 / 比較コンテキスト',
      output: '重要ポイント 4件 / 適合度 94',
      tool: 'OpenAI Structured Output',
      durationMs: 2840,
    },
    {
      id: 'risk',
      name: 'Risk Detection',
      purpose: '懸念点と不足情報を明確にする',
      status: 'completed',
      description: '契約条件と定例MTGの情報不足を検出しました。',
      input: '構造化された分析結果',
      output: 'リスク 2件 / 不足情報 2件',
      tool: 'Risk policy',
      durationMs: 214,
    },
    {
      id: 'recommendation',
      name: 'Recommendation',
      purpose: '次に取るべき行動を提案する',
      status: 'completed',
      description: '応募前の確認事項とアピールポイントを生成しました。',
      input: '分析結果 / リスク',
      output: '推奨アクション 3件',
      tool: 'Recommendation builder',
      durationMs: 731,
    },
    {
      id: 'final',
      name: 'Final Insight',
      purpose: '検証済みの成果物として確定する',
      status: 'completed',
      description: 'スキーマ検証後、分析結果を保存しました。',
      input: '全処理の構造化出力',
      output: 'recommendationScore: 92',
      tool: 'Zod + Supabase',
      durationMs: 126,
    },
  ],
  insight: {
    keyPoints: [
      'Next.js / TypeScriptの実務経験が必須要件と一致',
      'AIワークフロー設計を上流から担当できる',
      '週2〜3日かつフルリモートで希望条件に合致',
      '新規プロダクトの技術選定へ関与できる',
    ],
    risks: [
      '契約期間と更新条件が記載されていない',
      '定例MTGの曜日・時間帯が不明',
    ],
    actions: [
      '類似AIプロダクトの設計経験を中心に応募文を作成',
      '契約期間とMTG条件を応募前に確認',
      'SupabaseのRLS設計経験を具体例として添える',
    ],
    evidence: [
      '「Next.js / TypeScriptでの3年以上の開発経験」',
      '「生成AI機能の企画・設計・実装」',
      '「週2〜3日、フルリモート」',
    ],
    missingInformation: ['契約期間・更新条件', '定例MTGの実施条件'],
    confidence: 0.94,
    typeSpecific: [
      { label: 'Skill fit', value: '94 / 100' },
      { label: 'Condition fit', value: '91 / 100' },
      { label: 'Work style', value: 'フルリモート' },
      { label: 'Commitment', value: '週2〜3日' },
      { label: 'Rate', value: '80〜110万円 / 月' },
      { label: 'Career value', value: 'High' },
    ],
  },
};
